### PR TITLE
Using new snap and circuit

### PR DESCRIPTION
**Pull request by tomdele**

### CODE REVIEW

**Comment by tomdele** [comment]
The path to the circuit is obviously wrong (used a local one from mike) because the circuit was not updated back in the days.
Is the new sonata circuit available ?

**Comment by antonelepfl** [comment]
@mgeplf Can you tell me where is the circuit and if you copy it to the NOTO backend?
I'm not aware of any new path of this circuit

**Comment by antonelepfl** [comment]
@mgeplf Can you give some clarification with this? @tomdele did you try with the circuit that is currently in NOTO?

**Comment by tomdele** [comment]
No I did not because I had to test the analyses with a --pre version/ hacked version of snap. To do so, @mgeplf provided a multi population circuit for the moocs that I used locally to test the snap version and to migrate the bluepy codes to snap codes.
See:
https://bbpteam.epfl.ch/project/issues/browse/NSETM-932

**Comment by tomdele** [comment]
Now the snap version 0.2.0 is released, so we can run most of the notebooks with the circuit provided in the ticket(see comment above). 
Unfortunately, we still have the morphology format problem: using `.h5` instead of `.swc`. And maybe we will need to build a new circuit instead of converting the morphology files.

**Comment by wvangeit** [comment]
Could I suggest we run BGLibPy tests on this circuit (once it's ready) ? (Doing a similar exercise for thalamus unearthed 3 bugs)

**Comment by antonelepfl** [comment]
@tomdele @haleepfl If we have here some notebooks that re not blocked by the circuit / simulation can we merge them? Probably creating a new PR (?) with those notebooks only, so Alex can start testing them

**Pull request closed without merging**
