### PR TITLE
bluepy.sonata -> bluepysnap

### PR DESCRIPTION
**Pull request by arsenius7**
* make better use of BluePy API at some places:
   - `len(circ.cells.get())` -> `circ.nodes.size`
   - `numpy.random_choice(circ.cells.ids(...), n, ...)` -> `circ.cells.ids(..., sample=n)`
   - pass cell groups explicitly, without resolving to IDs
   - `cells.get(['x', 'y', 'z'])` -> `cells.positions()`
   - etc

### CODE REVIEW

**Comment by arsenius7** [comment]
'common_neighbour_2' notebook dies with `MemoryError` as it does on current `master`.

**Comment by arsenius7** [comment]
The diff is not particularly readable here; just in case: I have removed 'sonata' folder with notebook duplicates.

**Comment by arsenius7** [comment]
Stefano, Thomas, mind if I merge this one?

**Comment by antonelepfl** [comment]
I need to sync this in the Collab and check if the notebooks works in there.
Give me some time and I'll comment here

**Comment by antonelepfl** [comment]
The notebooks are fine (except what Arseny mentioned above. You can check the 'common_neighbour_2' error [here](https://collab.humanbrainproject.eu/#/collab/33645/nav/387897)).

@MWolfR Can you check that notebook please?

**Comment by arsenius7** [comment]
Most likely it's a problem on our side (due to NRN -> SONATA migration).
Given that this change does not aggravate it, I would suggest to merge it if we are fine with it otherwise; and investigate out of memory issue in a separate GitHub ticket.
For that we'll need an example of the circuit and / or code, where the analysis conducted in 'common_neighbour_2' worked.

**Comment by antonelepfl** [comment]
Ok it's fine then

**Comment by arsenius7** [comment]
> investigate out of memory issue in a separate GitHub ticket

#11

**Pull request merged**
