### PR TITLE
Snap multipop

### PR DESCRIPTION
**Pull request by tomdele**
The new notebooks for the new circuit. 

The new circuit has been given to @antonelepfl and is available on gpfs at: 
 /gpfs/bbp.cscs.ch/project/proj42/circuits/CA1.O1/mooc-circuit/

Everything works (for the analysis part, I have no idea about the result uploads for the exercises) except the simulations notebook. I need to finish the plotting part in snap and we need to produce the simulations (probably convert them I don t know) and creating the simulation_config.json for the notebook.

### CODE REVIEW

**Comment by antonelepfl** [comment]
Regarding the new API for plots and groups (mentioned in the stand up)..:
After I test this notebooks should I:
1) merge it and start a new PR for plot
2) notify you and then you will add the next changes (plot, groups, etc) in this branch?

Not very sure if the groups is related to the multipop

**Comment by tomdele** [comment]
You can test them and merge them now if everything runs well.
One notebook must fail: the one with the plots about the simulations. 

When the group + plotting parts are done in snap I will change the notebooks again. 

The `group` we mentioned is a change in the api due to a misleading naming convention we are using currently. Group refers to the last subdivision in the sonata format : `nodes/population/group` and we are using the name for something else in snap.
 
We are using this notation : 
```
ids = node.ids(group={a query})
```
to do a query and we will change it to:
```
ids = node.ids(query={a query})
```
or something equivalent.

**Comment by antonelepfl** [comment]
I checked the notebooks after changing the paths and the status are:

Please check [Overall status notebooks #167](https://github.com/BlueBrain/mooc-grading-service/issues/167) for a table with status

So as you mentioned we have to still make some changes on the notebooks to make them fully work but I just wanted to give an update from my side

**Comment by tomdele** [comment]
That s very useful thank you. 
Excitatory should exists in the node_sets.json this is strange.

**Comment by mgeplf** [comment]
@tomdele Any luck looking at this?

**Comment by tomdele** [comment]
I checked on the local circuit on gpfs and I did not have problem accessing the Excitatory node_sets. 
So I don t know if the node_sets.json has been correctly copied to NOTO or if I changed it afterwards for some reasons ....

**Comment by antonelepfl** [comment]
In NOTO the node_sets.json has that Excitatory IIRC but you can always check it by yourself following the instructions on this repo's README.

**Comment by tomdele** [comment]
Ok. I need to recheck then.

**Comment by tomdele** [comment]
Ok so I checked with @antonelepfl and I think the problems comes from a bad version of bluepysnap. 

@antonelepfl tried with the new version of snap and the Excitatory has been found.

**Comment by antonelepfl** [comment]
So the packages on NOTO were updated and I don't see the error anymore.
@alex4200 Could you have a last view to the notebooks and update the table from [above]( https://github.com/BlueBrain/MOOC-hippocampus-network-simulation-2019/pull/17#issuecomment-635960190)

**Comment by antonelepfl** [comment]
Hmm there is a commit fd0c680b671b9123c23268241918f7189961097f that I don't like it.
I'll try to revert it so it does not mess up the notebooks.

**Comment by antonelepfl** [comment]
I have updated the results [table](https://github.com/BlueBrain/MOOC-hippocampus-network-simulation-2019/pull/17#issuecomment-635960190)

**Comment by tomdele** [comment]
I need to check the external_innervation pb this is strange

**Comment by antonelepfl** [comment]
I guess this PR won't be merged due we:
* Already cherry-pick some notebooks (https://github.com/BlueBrain/MOOC-hippocampus-network-simulation-2019/commit/ac4bed72c2a24bcdce6071660fc0228f6b1f9aff)
* We did the PR of the simulation notebooks (https://github.com/BlueBrain/MOOC-hippocampus-network-simulation-2019/pull/24)

**Comment by tomdele** [comment]
Yes indeed we can abandon this PR

**Pull request closed without merging**
