### PR TITLE
Armando improved descriptions

### PR DESCRIPTION
**Pull request by antonelepfl**
@alex4200 Can you have a look at the notebooks changes?

### CODE REVIEW

**Comment by alex4200** [comment]
It looks like the changes contain a lot of output, i.e. executed cells. I don't think we want that. 

@romani79 Can you please upload the changed notebooks again, but with having cleared all output before? 

Thanks

**Comment by haleepfl** [comment]
FYI you can clear output in a jupyter notebook using the following on the command line:
`jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace your_input_file_name.ipynb`

**Comment by romani79** [comment]
I cleaned up the output and amended the commit.

**Comment by antonelepfl** [comment]
I don't see the latest changes in this branch

**Comment by antonelepfl** [comment]
@alex4200 can you have a quick look at the new descriptions / improvements ?

**Comment by alex4200** [comment]
I had a look and fixed some small issues (typos, spelling, periods, exercises). I think they are ok now and can be merged.

**Pull request merged**
