### PR TITLE
Add Simulations and LFP notebooks

### PR DESCRIPTION
**Pull request by antonelepfl**

### CODE REVIEW

**Comment by antonelepfl** [comment]
@romani79 You can check the change that I did to the notebook [here](https://github.com/BlueBrain/MOOC-hippocampus-network-simulation-2019/blob/aae44e4ba3092dd0111cb06dac1b3f29e6e9f5f3/notebooks/comparing_simulations.ipynb) I modified only below `Exercise #1` title

**Comment by antonelepfl** [comment]
After Armando review / add information @alex4200 can test this notebooks and the exercises to see how difficult is for the students to resolve them.

**Comment by antonelepfl** [comment]
@romani79 I don't get why you did this merge. We agreed that you would modify the notebook and then Alex would test it

**Comment by romani79** [comment]
Alex asked me to work on the pull request.
I thought I had to check the content and merge it if it was ok.
Please, remind me if I have to fix something there.

**Comment by antonelepfl** [comment]
@romani79 You were suppose to add more information to the student to 'guide' him to resolve the exercise, with some documentation or pre-done code.

**Pull request merged**
