### PR TITLE
SONATA analogues of some usecases

### PR DESCRIPTION
**Pull request by arsenius7**
These are SONATA counterparts for usecases:
* common_neighbour_1
* common_neighbour_2
* density_analysis

### CODE REVIEW

**Comment by antonelepfl** [comment]
Before merge this
- Merge with the latest change on the Collab notebooks
- ~~Change Import of Sonata from devpi to 'open source' one~~

**Comment by arsenius7** [comment]
Getting open-sourced one will probably take some time.
If collab notebooks are to be evolved (or new added), it might be easier to switch to internal `bluepy.sonata` now and stick with it, rather than wait, to ensure easy switch to open-sourced one later.

**Comment by arsenius7** [comment]
> switch to internal `bluepy.sonata` now and stick with it, rather than wait, to ensure easy switch to open-sourced one later.

@jdcourcol will communicate the request to switch to `bluepy.sonata` to usecase authors.

@mgeplf , can we look into SONATA-fying the usecase with projections in this or another PR?
Thanks.

**Comment by mgeplf** [comment]
We're right in the middle of changing the projections again, so we may as well do it in another PR.

**Comment by arsenius7** [comment]
@antonelepfl , are we good with merging it now after your changes?

**Comment by antonelepfl** [comment]
Sure

**Pull request merged**
