### PR TITLE
Fixes for comparing_simulations notebook

### PR DESCRIPTION
**Pull request by alex4200**
Fixed some typos on the _comparing_simulations_ notebook

### CODE REVIEW

**Comment by antonelepfl** [comment]
Thank you Alex!

Do you think based on what you tested that we should include something else on the notebook or is it fine?

**Comment by alex4200** [comment]
As mentioned yesterday, I never would have come to the conclusion to use expressions like

`sim.circuit.nodes["hippocampus_neurons"].ids(group={"$node_set": target},sample=None) `

or 

`sim.spikes.filter([gid], t_start=t_start, t_stop=t_end).report`

in the exercise. I do not know what it means. 

If there is no other mention or documentation during the course to this point explaining these expressions, I suggest to add some explanation.

**Comment by antonelepfl** [comment]
@romani79 is there any update?

**Comment by antonelepfl** [comment]
@romani79 and this one? any update?

**Pull request closed without merging**
