### PR TITLE
Fix external_innervation

### PR DESCRIPTION
**Pull request by tomdele**
* This notebook had problems due to NOTO memory limitations.  To reduce memory usage we now sample the edge_ids to retrieve for
  the positions
* Add a fixed seed for the sampling
* Print warning when the cell is long to process

### CODE REVIEW

**Comment by tomdele** [comment]
The sampling to 500000 corresponds to 2 minutes processing. 
This is a ok trade off between waiting and having a correct plot at the end. 
@romani79 are you happy with this ?

**Review by jdcourcol — COMMENTED** [review]
Thank you for the fix.
I would suggest to call tqdm on the 'proj_conn.iter_connections' call as it takes 6 min. That would show the end user that something is happening

**Comment by tomdele** [comment]
Yep sure makes sense.

**Comment by jdcourcol** [comment]
@romani79 May be you are not done with that notebook. I think it deserves some text to explain what is going on, and some illustration showing the external innervation

**Comment by tomdele** [comment]
Just remembered why I never use tqdm and specially with a lot of short iterations.

Without tqdm : 
```
for p in proj_conn.iter_connections(pre, post, return_edge_count=True):
CPU times: user 2min, sys: 1.79 s, total: 2min 2s
Wall time: 4min 10s
```
We don t know the exact number of iterations (I am looping over an iterator) but we know the number of iterations should be close to `proj_conn.size` so I am using `total=proj_conn.size` to have a progress bar and not just the number of iterations per second.

With  `tdqm.notebook` : 
```
from tqdm.notebook import tqdm
for p in tqdm(proj_conn.iter_connections(pre, post, return_edge_count=True), total=proj_conn.size):

~20 minutes to process
```

With normal tqdm : 
```
from tqdm import tqdm
for p in tqdm(proj_conn.iter_connections(pre, post, return_edge_count=True), total=proj_conn.size):
 93%|█████████▎| 31715709/33920696 [09:18<00:38, 56756.82it/s] 
```
\+ I had one random fail (soft lock maybe because `total` is a bit superior to the real number of iterations no idea).

Without the `total=proj_conn.size`
```
for p in tqdm(proj_conn.iter_connections(pre, post, return_edge_count=True)):
31715709it [09:04, 58297.66it/s] 
```
Or we can go with the classic that does not reduce the perfs and print something less fancy :

```
print_at = int(proj_conn.size / 10)
for i, p in enumerate(proj_conn.iter_connections(pre, post, return_edge_count=True)):
    data[p[2]] += 1
    if i % print_at == 0:
        print(str(i) + '/ ' + str(proj_conn.size) + ' iterations')
```
~ 4m20

I will go for the last one.

**Comment by tomdele** [comment]
Did not mention it but, we can do better with tqmd but at the end I think this is even more confusing than the print because it hides a bit the important function which is the iter_connections : 
```
for p in tqdm(proj_conn.iter_connections(pre, post, return_edge_count=True), maxinterval=3600, miniters=int(proj_conn.size / 10)):
~ 4 minutes 40s
```

@romani79 let me know what you prefer and think is the less confusing.

**Comment by antonelepfl** [comment]
It works for me too. Thank you Tom!

**Comment by romani79** [comment]
I agree with Thomas that the option with print may be less elegant but for sure more clear for a beginner. I would vote for 'print'.

**Pull request merged**
